name: Create Sponsors Section PRs

on:
  workflow_dispatch:

jobs:
  sponsors-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_BOT_TOKEN }}" | gh auth login --with-token

      - name: Prepare and create PRs
        run: |
          git config --global user.email "sponsors-bot@hellang.com"
          git config --global user.name "Sponsors Bot"
          git config --global url.https://${{ secrets.GH_BOT_TOKEN }}@github.com/.insteadOf https://github.com/

          BRANCH_NAME="add-sponsors-section"
          PR_TITLE="Add Sponsors section to README"
          PR_BODY="This adds the standard Sponsors section to the README."

          gh repo list khellang --source --visibility public --no-archived --limit 100 --json nameWithOwner \
            | jq -r '.[] | .name' | while read repo; do

            if [ "$repo" = "EFCore.Sqlite.NodaTime" ]; then
              echo "Skipping $repo (explicit exception)"
              continue
            fi

            echo "Cloning $repo..."
            gh repo clone "khellang/$repo" -- --depth=1
            cd "$repo" || continue

            DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
            echo "Detected default branch: $DEFAULT_BRANCH"
            git checkout "$DEFAULT_BRANCH"
            git reset --hard

            git checkout -B "$BRANCH_NAME"

            if [ -f README.md ]; then
              echo "Processing README.md..."

              # Strip existing Sponsors section
              awk '
                BEGIN { skip=0 }
                /^## Sponsors/ { skip=1; next }
                /^## [^ ]/ && skip==1 { skip=0 }
                skip==0 { print }
              ' README.md > README.tmp && mv README.tmp README.md

              REPO="$repo"
              SPONSORS_SECTION=$(env REPO="$REPO" envsubst < ../.github/sponsors.template.md)
              
              echo "$SPONSORS_SECTION" >> README.md
            
              if git diff --quiet; then
                echo "No change in README – skipping commit."
              else
                git add README.md
                git commit -m "$PR_TITLE" || echo "Nothing to commit"
                git push origin "$BRANCH_NAME" --force
                
                # Check if PR already exists
                if ! gh pr list --head "$BRANCH_NAME" --state open --json number -q '.[0]'; then
                  gh pr create \
                    --title "$PR_TITLE" \
                    --body "$PR_BODY" \
                    --head "$BRANCH_NAME" \
                    --reviewer khellang \
                    --assignee khellang
                else
                  echo "PR already exists for $repo – updated branch with force push."
                fi
              fi
            else
              echo "README.md not found – skipping."
            fi

            cd ..
            rm -rf "$repo"
          done
